require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstancesController do

  # This should return the minimal set of attributes required to create a valid
  # Instance. As you add validations to Instance, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all instances as @instances" do
      instance = Instance.create! valid_attributes
      get :index
      assigns(:instances).should eq([instance])
    end
  end

  describe "GET show" do
    it "assigns the requested instance as @instance" do
      instance = Instance.create! valid_attributes
      get :show, :id => instance.id
      assigns(:instance).should eq(instance)
    end
  end

  describe "GET new" do
    it "assigns a new instance as @instance" do
      get :new
      assigns(:instance).should be_a_new(Instance)
    end
  end

  describe "GET edit" do
    it "assigns the requested instance as @instance" do
      instance = Instance.create! valid_attributes
      get :edit, :id => instance.id
      assigns(:instance).should eq(instance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Instance" do
        expect {
          post :create, :instance => valid_attributes
        }.to change(Instance, :count).by(1)
      end

      it "assigns a newly created instance as @instance" do
        post :create, :instance => valid_attributes
        assigns(:instance).should be_a(Instance)
        assigns(:instance).should be_persisted
      end

      it "redirects to the created instance" do
        post :create, :instance => valid_attributes
        response.should redirect_to(Instance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instance as @instance" do
        # Trigger the behavior that occurs when invalid params are submitted
        Instance.any_instance.stub(:save).and_return(false)
        post :create, :instance => {}
        assigns(:instance).should be_a_new(Instance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Instance.any_instance.stub(:save).and_return(false)
        post :create, :instance => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested instance" do
        instance = Instance.create! valid_attributes
        # Assuming there are no other instances in the database, this
        # specifies that the Instance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Instance.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => instance.id, :instance => {'these' => 'params'}
      end

      it "assigns the requested instance as @instance" do
        instance = Instance.create! valid_attributes
        put :update, :id => instance.id, :instance => valid_attributes
        assigns(:instance).should eq(instance)
      end

      it "redirects to the instance" do
        instance = Instance.create! valid_attributes
        put :update, :id => instance.id, :instance => valid_attributes
        response.should redirect_to(instance)
      end
    end

    describe "with invalid params" do
      it "assigns the instance as @instance" do
        instance = Instance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Instance.any_instance.stub(:save).and_return(false)
        put :update, :id => instance.id, :instance => {}
        assigns(:instance).should eq(instance)
      end

      it "re-renders the 'edit' template" do
        instance = Instance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Instance.any_instance.stub(:save).and_return(false)
        put :update, :id => instance.id, :instance => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instance" do
      instance = Instance.create! valid_attributes
      expect {
        delete :destroy, :id => instance.id
      }.to change(Instance, :count).by(-1)
    end

    it "redirects to the instances list" do
      instance = Instance.create! valid_attributes
      delete :destroy, :id => instance.id
      response.should redirect_to(instances_url)
    end
  end

end
